// Generated by CoffeeScript 1.6.3
(function() {
  var corsify, fetch, http, port, server, url;

  http = require('follow-redirects').http;

  url = require('url');

  port = process.argv[2] || process.env.PORT || 3000;

  corsify = function(res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET');
    return res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  };

  fetch = function(url, endPipe) {
    var req;
    req = http.get(url, function(res) {
      return res.pipe(endPipe);
    });
    return req.on('error', function(e) {
      console.error(e);
      return endPipe.end();
    });
  };

  server = http.createServer(function(req, res) {
    var location;
    location = url.parse(req.url, true).query.url;
    if (location) {
      console.log("Got a request for " + location);
      corsify(res);
      return fetch(location, res);
    } else {
      return res.end();
    }
  });

  server.listen(port, function() {
    return console.log("Server listening on port " + port);
  });

}).call(this);
